"use client";

import { useEffect, useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useAdmin } from '@/hooks/useAdmin';
import { getPendingHighlightsAction, approveHighlightAction, rejectHighlightAction } from '@/app/actions/admin';
import { Loader2, CheckCircle, XCircle, Clock, ExternalLink } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import Link from 'next/link';

export default function PendingHighlightsPage() {
  const { isAuthorized, loading } = useAdmin(true);
  const [pending, setPending] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    async function load() {
      setIsLoading(true);
      const res = await getPendingHighlightsAction();
      if (res.success) setPending(res.data);
      setIsLoading(false);
    }
    if (isAuthorized) load();
  }, [isAuthorized]);

  const handleApprove = async (repId: string, highlightId: string) => {
    setProcessingId(highlightId);
    const res = await approveHighlightAction(repId, highlightId);
    if (res.success) {
      toast({ title: 'Approved', description: res.message });
      setPending(prev => prev.filter(p => p.id !== highlightId));
    } else {
      toast({ variant: 'destructive', title: 'Failed', description: res.error });
    }
    setProcessingId(null);
  };

  const handleReject = async (repId: string, highlightId: string) => {
    setProcessingId(highlightId);
    const res = await rejectHighlightAction(repId, highlightId, 'Admin rejected');
    if (res.success) {
      toast({ title: 'Rejected', description: res.message });
      setPending(prev => prev.filter(p => p.id !== highlightId));
    } else {
      toast({ variant: 'destructive', title: 'Failed', description: res.error });
    }
    setProcessingId(null);
  };

  if (loading || isLoading) {
    return (
      <MainLayout>
        <div className="flex justify-center py-20">
          <Loader2 className="h-12 w-12 animate-spin" />
          <p className="ml-4">Loading pending highlights...</p>
        </div>
      </MainLayout>
    );
  }

  if (!isAuthorized) return null;

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold font-headline">Pending Highlights Review</h1>
            <p className="text-muted-foreground">AI-generated highlights queued for human-in-loop approval (AI Governance Control)</p>
          </div>
          <Button asChild variant="outline"><Link href="/dashboard/admin">Back to Admin</Link></Button>
        </div>

        {pending.length === 0 ? (
          <Card>
            <CardContent className="py-20 text-center">
              <CheckCircle className="h-16 w-16 text-green-500 mx-auto mb-4" />
              <h3 className="text-xl font-semibold">No pending highlights</h3>
              <p className="text-muted-foreground mt-2">All AI outputs have been reviewed. Good job!</p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid gap-6">
            {pending.map((item) => (
              <Card key={item.id} className="border-l-4 border-l-yellow-500">
                <CardHeader>
                  <div className="flex justify-between items-start">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        {item.title}
                        <Badge variant="outline" className="bg-yellow-50">{item.category}</Badge>
                      </CardTitle>
                      <CardDescription className="mt-1">
                        Rep: <Link href={`/representatives/${item.representativeSlug}`} className="text-primary hover:underline">{item.representativeName}</Link> • 
                        Date: {item.date ? new Date(item.date).toLocaleDateString() : 'N/A'} • 
                        Generated by: {item.generatedBy || 'system'}
                      </CardDescription>
                    </div>
                    <Badge variant="secondary" className="flex items-center gap-1">
                      <Clock className="h-3 w-3" /> Pending
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-sm leading-relaxed">{item.description}</p>
                  
                  {item.sourceUrl && (
                    <a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-sm text-primary hover:underline flex items-center gap-1">
                      Source: {item.sourceUrl} <ExternalLink className="h-3 w-3" />
                    </a>
                  )}

                  <div className="flex gap-3 pt-2">
                    <Button
                      onClick={() => handleApprove(item.representativeId, item.id)}
                      disabled={processingId === item.id}
                      className="bg-green-600 hover:bg-green-700"
                    >
                      {processingId === item.id ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <CheckCircle className="h-4 w-4 mr-2" />}
                      Approve & Publish
                    </Button>
                    <Button
                      onClick={() => handleReject(item.representativeId, item.id)}
                      disabled={processingId === item.id}
                      variant="destructive"
                    >
                      <XCircle className="h-4 w-4 mr-2" /> Reject
                    </Button>
                    <Button asChild variant="outline">
                      <Link href={`/representatives/${item.representativeSlug}`}>View Rep</Link>
                    </Button>
                  </div>

                  <div className="text-xs text-muted-foreground bg-muted p-2 rounded">
                    <strong>AI Governance:</strong> This highlight was AI-generated from tweets/news. Must verify source URL before approval. Check for defamation, bias, hallucinations. Per Kenya DPA, ensure verifiable.
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </MainLayout>
  );
}
